import Head from "next/head";
import { Inter } from "next/font/google";

import Navbar from "@/components/global/navbar/Navbar";
import { useDispatch, useSelector } from "react-redux";
import { fetchData, setTheme } from "@/redux/app/theme/themeSlice";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(fetchData("theme"));
  }, [dispatch]);

  const theme = useSelector((state) => state.theme.theme);

  return (
    <>
      <Head>
        <title>Rahmat Ali</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{ backgroundColor: `${!theme === "light" ? "black" : "white"}` }}
      >
        <Navbar />
      </main>
    </>
  );
}
